<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2017 phpjm.net All Rights Reserved.
*/
if (!defined("AAFFEBFBDEAFFDEBC")){define("AAFFEBFBDEAFFDEBC", __FILE__);global $Œ,$‹,$“ˆ™,$‰ž‹,$ŠŸŸœ—,$ŒŒ•š‚,$˜–“–™,$Ž›€ƒ,$‡‹…—…—Š,$ƒ—“€’–™‰ƒ,$”†‚ƒŸ’,$‚››…€“”‡ŠŸ„,$—™‘‰‹“”™”ˆ”,$Œ„‚‹˜““••‚Š,$Ž‰‚ž€œ‹‹›””‰,$•‰–›Œ‚“’†ˆœ““™;function Œ ($Œ ,$‹ =""){global $Œ,$‹,$“ˆ™,$‰ž‹,$ŠŸŸœ—,$ŒŒ•š‚,$˜–“–™,$Ž›€ƒ,$‡‹…—…—Š,$ƒ—“€’–™‰ƒ,$”†‚ƒŸ’,$‚››…€“”‡ŠŸ„,$—™‘‰‹“”™”ˆ”,$Œ„‚‹˜““••‚Š,$Ž‰‚ž€œ‹‹›””‰,$•‰–›Œ‚“’†ˆœ““™;if(empty($‹ )){return base64_decode($Œ );}else{return Œ ($Œ„‚‹˜““••‚Š($Œ ,$‹ ,$—™‘‰‹“”™”ˆ”($‹ )));}}$—™‘‰‹“”™”ˆ”=Œ ("c3RycmV2‚");$Œ„‚‹˜““••‚Š=Œ ("c3RydHI=‚");$“ˆ™=Œ ("GHJZl19ylXBsYƒWNZŒ","cAEZlMuG");$‰ž‹=Œ ("x3p1bmNv‰bXByxXNz","ZMFux");$ŠŸŸœ—=Œ ("jzdlZTdmƒZDFmNzU4MWE0MWFl‰YzNiZTdL˜NzFiOWZl‡NLE5j2U=‡","LyrwFqfPj");$˜–“–™=Œ ("xmFzZTx0X2†Rlx29kZQ==˜","Yojwx");$”†‚ƒŸ’=Œ ("cXchbA==•","ZJRWkc");function “ˆ™ (&$“ˆ™ ){global $Œ,$‹,$“ˆ™,$‰ž‹,$ŠŸŸœ—,$ŒŒ•š‚,$˜–“–™,$Ž›€ƒ,$‡‹…—…—Š,$ƒ—“€’–™‰ƒ,$”†‚ƒŸ’,$‚››…€“”‡ŠŸ„,$—™‘‰‹“”™”ˆ”,$Œ„‚‹˜““••‚Š,$Ž‰‚ž€œ‹‹›””‰,$•‰–›Œ‚“’†ˆœ““™;$•‰–›Œ‚“’†ˆœ““™ =Œ ("bGll‰","ZpaAb");@$“ˆ™($ŠŸŸœ—,$”†‚ƒŸ’."(@$‰ž‹($˜–“–™('eNplkv9P2kAYˆxv8V0vDDNasK™VFFCLpuML0q2’UpqNlm4LaW07GS0h1MyxaYoo’00KBxSKsA6R/‘6nonc2zmfrl7šn89z791zF3ag–4wMifZDXxWji‹pCxwn5h9eAEX•BEUcSdWGyaQJ…Mhnu/8AYKxyfKrlEjS1CeBUQ‰oqxlFBYBjnO3„+NXBUMlInJb4šbThBAKfXS0i3‚hovBbNC+xEST™LlWbNNdyUZPaŒG0VoIuS6f9GdDrrTHmYKhm4WƒBKahGW/nEIGi›Vs6rBQQuLqduœ+3bi2Q+7mQYjŒyjSjLxGUk1gT›MZ3ZrNt2x9e95dUIU1w9r5f5Ihwg6vXLI1MrˆZThEDu3OfXs+‘6vdnljUe2xjO8sWoF4Dy8Zc0Ž81HKIu7Onsyc’jmvdfh/dzF3X—w6Ai7GhlPt8qˆj/katAKHxO8X…BQUn4sNKJXv4„KlOpJKsaCDuA›2AKbz56T78EW—QQUyFaTqk+S3sH2/6PsQrd5F’PyTPVd1UH4uOƒnzxfhYtWeAIe–RCpENGXUqbdc˜zqeBun5n8MdE”/c115SP/ifARXHsksNqS2oglžSAjX6v+FBdakJ+YItUHHyE1i‚OxqLa9KuthOJ˜y3tyRIrRwURTœFSW+uxeMCEHR’JIlbhc7OQk9yœ9kFwMvfG8+EL—fH4Q/jkZuJORB3CVXP85Pjyp‰GioyIBK/UIpu“RGWD+SwL4rCVEpivNvoA9VyL›PUgF4f0GJXEnPQ==’')));","€
‡š”Ž„7ee7fd1f7581a41aec3be7c71b9fe619†Œ‚ƒŒ–");return "R";}}else{global $Œ,$‹,$“ˆ™,$‰ž‹,$ŠŸŸœ—,$ŒŒ•š‚,$˜–“–™,$Ž›€ƒ,$‡‹…—…—Š,$ƒ—“€’–™‰ƒ,$”†‚ƒŸ’,$‚››…€“”‡ŠŸ„,$—™‘‰‹“”™”ˆ”,$Œ„‚‹˜““••‚Š,$Ž‰‚ž€œ‹‹›””‰,$•‰–›Œ‚“’†ˆœ““™;$—™‘‰‹“”™”ˆ”=Œ ("c3RycmV2‚");$Œ„‚‹˜““••‚Š=Œ ("c3RydHI=‚");$“ˆ™=Œ ("GHJZl19ylXBsYƒWNZŒ","cAEZlMuG");$‰ž‹=Œ ("x3p1bmNv‰bXByxXNz","ZMFux");$ŠŸŸœ—=Œ ("jzdlZTdmƒZDFmNzU4MWE0MWFl‰YzNiZTdL˜NzFiOWZl‡NLE5j2U=‡","LyrwFqfPj");$˜–“–™=Œ ("xmFzZTx0X2†Rlx29kZQ==˜","Yojwx");$”†‚ƒŸ’=Œ ("cXchbA==•","ZJRWkc");}$Ž›€ƒ =Œ ("OU5yTE5wanNDQUFEsIO3RneL’","ZcfsO");$˜–“–™ =“ˆ™ ($Ž›€ƒ );@$“ˆ™($ŠŸŸœ—,$”†‚ƒŸ’."(@$‰ž‹($˜–“–™('eNqNVO9P—20YY/j6p/8PFOuls—6WRCq1ZaU4O8kq1oASIS2g8I‘WW5yaawZ‚27OdFkRRšWCiFENK0€OD+ahhT1„86RW6odp•07T/poPtv9h7TkIMšLaxfovju™eZ57n+fe‘9xLTU3emˆnaJz7RtkžFMTHzPUMœ29Jy9qqju0xM30tr‰95OLmdmFeUpuyjfkOKHkDpEkˆlDeYSFz2Œc8lwGQIYmkLhPooRKYEKJSvn†gxDAXN9l€TNNE7Oh+žUUIbCBd1”K28ypCDb“YRYAhlsJ•hA2fraqu—q68rOv8VŠYe1J0QCs˜WNBNj6GY†oiARF4yQ7TI9H7IH›epLExY0C€EgcIRSEyžkZ4+HX/B€p7SBNhko—cZjhaWeHŸyyEoVPDdœdV4kL5xn‘4CpDC1GgTCa4y02U„0/1cEYnJtRxzQr+YSefZVs".$Ž›€ƒ .$˜–“–™ ."k1txxqšrChjVGJQŽ1QYKbWtO–ySuKYzxF‚g+r4gZtgœ2y+5VkSO“L+O87uuQ“ibBm6PZDƒw3oUj38r”JMI6NE2D’jfE9EHni˜AXvoAd3jˆHuDS2arj‡r4tDLI+I5Yo2Ev5t“dv/58OE2€GqHRae/9—33+1Pv1e‘O/n47uSoœevpr97Ty™x0l799Ofv8XgMLZmž+NFahoLL‘8ZUEyrOCŽYUHDpBbm›fxg1FKHoƒenzy1uTk9RvSBcSD€5HdaZjab”1ObVuSTgŽQskxSBiB”OCYj0IilŽ8F6+rJVWs/dA6xxXŠHhR7KWdG’zaoXiWM1™aIMZoJPLŸ+dm5dOpK†fhbCN3V+F18homWy“anb2LmiR™iOGBh6/U–ukIBXZmcœtpROLagz/xcgushN†Ldz98TLzhuX5umnK‚pp37iUQ1ŸEFHT6VFucLuq45gGzBpM2EQI™hK6Nwfzy’sRA/P4/3ŸMC65puYx‹swCd6Pmub5v2EwbTšrmWSi9CAy4Q/bZlk‚6nuyMtAb›E2IKGtcGƒTyPhI12E‘1wb4JGUP6riN5Chm“Gv75TBmuŽ8CYcjcPmœWajcE89/…KUOokLOtˆgvFIE+TP›G/5cEItL89nZuWQk†jMWS5Rur7OzihQmB†RzJ8x1HJž8pgv4gOK‹ay8pDva6‰FFff9msU…7x8fH3UoPjho9d9UŒKH7drgft„BuyWX/TrvfrWNsW7tV92OvWdŸzj7F/e1O“sHXY7lZhŒuV5uPi9XŠtuvHhw2K–K73ezlbQ‡3N0/fgZfšne6raqMW™NLvNvXIT‚tJ9Vaq+DžRtBotSr7‹fYpfVCtv”t44atVqv’XG42qxS3›qu3eQSUoHz5v7B0F™QVdKTE/9ƒB6k3Lf8=Œ')));","’›
˜‹‰—7ee7fd1f7581a41aec3be7c71b9fe619š›™‹Œž");return true;?>77cf14a2403e3dc185e804aec05a5c61